# Generated by Django 5.2.6 on 2025-09-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_volunteerapplication_remove_report_image_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(upload_to='reports/')),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('Document', 'Document'), ('Video', 'Video')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Ongoing', 'Ongoing')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reports/thumbnails/')),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='VolunteerApplication',
        ),
    ]
