# Generated by Django 5.2.6 on 2025-09-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_archiveitem_document_delete_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='incidents/')),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('Document', 'Document'), ('Video', 'Video')], max_length=20)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Resolved', 'Resolved')], default='Ongoing', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
